languageCode: "en"
baseUrl: "https://elibroftw.github.io/"
title: "ELL Blog"
theme: "anubis"
paginate: 10
disqusShortname: ""
googleAnalytics: ""
enableRobotsTXT: true
publishDir: docs
contentDir: ["posts"]

menu:
  main:
  - identifier: homee
    name: Home
    title: Home
    url: /
    weight: 1
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags/
    weight: 0

params:
  author: "Elijah Lopez"
  email: elijahllopezz@gmail.com  # used for microformats
  avatar: "/images/me.png" # used for microformats
  description: ""
  # Uncomment if you need this
  images:
    - images          # path relative to "static" directory
  customCSS:  # path relative to "assets" directory (don't use main.css filename)
    - css/custom.css
  # customJS:
  #   - js/copy-button.js
  dateFormat: "2006-Jan-02"
  paginationSinglePost: true
  style: dark-without-switcher
  readMore: false
  disableSummary: true
  # utteranc.es support
  utterancesRepo: "elibroftw/elibroftw.github.io"  # mandatory
  utterancesTheme: "github-dark" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  webmentions:
    url: https://elibroftw.github.io/
    login: hugo-theme-anubis
    pingback: true
  social:
  - id: rss
    url: index.xml
  - id: github
    name: elibroftw
  - id: twitter
    name: elibroftw
  - id: youtube
    url: https://youtube.com/channel/UCIrKT6IOvPo_oT4zSUm6uhQ
  - id: email
    name: elijahllopezz@gmail.com

#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"

markup:
  highlight:
    style: rrt
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
