languageCode: "en"
baseUrl: "https://blog.elijahlopez.ca/"
title: "ELL Blog"
theme: "anubis"
paginate: 50
disqusShortname: ""
googleAnalytics: ""
enableRobotsTXT: true
publishDir: public
contentDir: content

menu:
  main:
  - identifier: home
    name: Home
    title: Home
    url: /
    weight: 1
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags/
    weight: 0
  # - identifier: about
  #   name: About
  #   title: About
  #   url: /about/
  #   weight: 0

params:

  author: "Elijah Lopez"
  # used for microformats
  email: elijahllopezz@gmail.com
  avatar: https://pbs.twimg.com/profile_images/1738729591064166400/vqarzcF7_400x400.jpg

  description: ""
  # Uncomment if you need this
  images:
    - images          # path relative to "static" directory
  customCSS:  # path relative to "assets" directory (don't use main.css filename)
    - css/custom.css
    - css/inline-spoiler.scss
  # customJS:
  #   - js/copy-button.js
  dateFormat: "January 2, 2006"
  paginationSinglePost: true
  style: dark
  readMore: false
  disableSummary: true
  # utteranc.es support
  utterancesRepo: "elibroftw/blog.elijahlopez.ca"  # mandatory
  utterancesTheme: "github-dark" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  # giscus support
  # GiscusRepo: "elibroftw/blog.elijahlopez.ca"  # mandatory
  # GiscusRepoId: "438500230" # mandatory
  # GiscusCategory: "General" # mandatory
  # GiscusCategoryId: "9f0abe34da433c9b6db74bffa2466494a717b579a96b30a5d252e5090baea7be" # mandatory
  # GiscusLazyLoad: false # optional
  # webmentions:
  #   url: https://elibroftw.github.io/
  #   login: hugo-theme-anubis
  #   pingback: true
  social:
  - id: rss
    url: /index.xml
  - id: website
    url: https://elijahlopez.ca
  - id: github
    name: elibroftw
  - id: twitter
    name: elibroftw
  - id: youtube
    name: elibroftw
  - id: email
    name: elijahllopezz@gmail.com
  # - id: instagram
  #   name: elijahllopezz

#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"


staticDir:
  - static
  - themes/anubis/static

markup:
  highlight:
    style: native
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
minify:
  tdewolff:
    html:
      keepWhitespace: false